import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import Navbar from "@/components/Layout/NavBar/Navbar";
import { Providers } from "../store/Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body>
        <Providers>

          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              themes={["dark", "rose", "darkRose", "green", "darkGreen", "blue", "darkBlue"]}
            >
            {/*nav bar  */}
            <Navbar />

            {/* content */}
            {children}

            {/* footer */}

          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
