import type { Metadata } from "next";
import { Providers } from "../store/Provider";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import ClientLayoutWrapper from "./ClientLayoutWrapper"


export const metadata: Metadata = {
  title: "Wonder Academy",
  description: "Generated by Adel & Norhan",
  icons: {
    icon: "/imgs/stack-of-books.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            themes={[
              "dark",
              "rose",
              "darkRose",
              "green",
              "darkGreen",
              "blue",
              "darkBlue",
            ]}
          >
            <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
